// Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied. See the License for the
// specific language governing permissions and limitations
// under the License.
import wso2/ai.agent;

# A raw test case generated by the agent
type TestCase record {|
    # Name of the tool (mapped to the API resource)
    string tool;
    # Input parameters for the tool
    map<json> tool_input = {};
|};

# A test case mapped to the API resource
type ApiResourceDefinition record {|
    # HTTP method of the resource
    string method;
    # Path of the resource
    string path;
    # Input parameters for the resource
    map<json>? inputs = ();
|};

# A test execution step. Stores the reasoning by the agent and http responses from the test run.
type TestExecutionStep record {|
    *agent:ExecutionStep;
    # HTTP response from a single test run
    agent:HttpOutput observation;
|};

# A test execution report. Stores the API resource and the test execution steps.
type NextAction record {|
    # Thought generated by the agent
    json llmResponse;
    # API resource executed by the agent
    ApiResourceDefinition 'resource;
|};

# Contains the spec for a single API resource
type ApiResource readonly & record {|
    # The path of the resource
    string path;
    # The HTTP method of the resource
    string method;
    # The spec of the resource
    agent:Operation spec;
|};

# Contains generated descriptions for a single API resource
type ApiResourceDescriptor record {|
    # The path of the resource
    string path;
    # The HTTP method of the resource
    string method;
    # The generated description for the resource
    string description;
|};

# Contains the generated sample queries
type GeneratedQuerySet record {|
    # Sample query for single API invocation 
    string singleResourceCall;
    # Sample query for multiple API invocations
    string multiResourceCall;
|};

# Sample query record
type SampleQuery record {|
    # Sample query scenario
    string scenario;
    # Generated sample query for the scenario
    string query;
|};

# Cached record with progress
type CacheRecord record {|
    # Current iteration
    int iteration;
    # Command to be executed
    string command;
    # Api specification
    agent:HttpApiSpecification apiSpec;
    # Execution history of the test agent
    TestExecutionStep[] executionHistory;
    # Thought during previous execution
    json previousLlmResponse?;
|};
