import os

CHOREO = "choreo"
APIM = "apim"

# streaming stage constants
START_STREAM = "START_STREAM"
FIND_LLM_RESPONSE = "FIND_LLM_RESPONSE"
SEND_LLM_RESPONSE = "SEND_LLM_RESPONSE"
END_LLM_RESPONSE = "END_LLM_RESPONSE"
FIND_API = "FIND_API"
SEND_API = "SEND_API"
BUFFER_API = "BUFFER_API"
FINISH_STREAM = "FINISH_STREAM"

ZILLIZ_CLOUD_URI = os.getenv('ZILLIZ_CLOUD_URI')
ZILLIZ_CLOUD_API_KEY = os.getenv('ZILLIZ_CLOUD_API_KEY')
AZURE_ENDPOINT = os.getenv('AZURE_ENDPOINT')
AZURE_EMBEDDING_DEPLOYMENT = os.getenv('AZURE_EMBEDDING_DEPLOYMENT', "OpenAPIEmbeddings")
AZURE_CHAT_DEPLOYMENT = os.getenv('AZURE_CHAT_DEPLOYMENT', "APIM-Deployment")
AZURE_CHAT_VERSION = os.getenv('AZURE_CHAT_VERSION', "2023-12-01-preview")
SOURCE_PLATFORM = os.getenv('SOURCE_PLATFORM')
PROXY_URL = os.getenv('PROXY_URL')

OUTPUT_FIELDS = ['id', 'metadata', 'api_type', 'api_name', 'page_content', 'org_id']
