openapi: 3.0.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /ai/api-chat/prepare:
    post:
      summary: Prepare
      operationId: prepare_ai_api_chat_prepare_post
      parameters:
        - required: false
          schema:
            type: string
            title: Apichatrequestid
          name: apiChatRequestId
          in: header
        - required: false
          schema:
            type: string
            title: Api-Key
          name: API-KEY
          in: header
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: Req
        required: true
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /ai/api-chat/execute:
    post:
      summary: Execute
      operationId: execute_ai_api_chat_execute_post
      parameters:
        - required: false
          schema:
            type: string
            title: Apichatrequestid
          name: apiChatRequestId
          in: header
        - required: false
          schema:
            type: string
            title: Api-Key
          name: API-KEY
          in: header
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: Req
        required: true
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /ai/marketplace-assistant/chat:
    post:
      summary: Chat
      operationId: chat_ai_marketplace_assistant_chat_post
      parameters:
        - required: false
          schema:
            type: string
            title: Api-Key
          name: API-KEY
          in: header
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: Req
        required: true
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /ai/spec-populator/publish-api:
    post:
      summary: Publish Api
      operationId: publish_api_ai_spec_populator_publish_api_post
      parameters:
        - required: false
          schema:
            type: string
            title: Api-Key
          name: API-KEY
          in: header
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: Req
        required: true
      responses:
        '201':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /ai/spec-populator/remove-api/{uuid}:
    delete:
      summary: Remove Api
      operationId: remove_api_ai_spec_populator_remove_api__uuid__delete
      parameters:
        - required: true
          schema:
            type: string
            title: Uuid
          name: uuid
          in: path
        - required: false
          schema:
            type: string
            title: Api-Key
          name: API-KEY
          in: header
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /ai/spec-populator/api-count:
    get:
      summary: Api Count
      operationId: api_count_ai_spec_populator_api_count_get
      parameters:
        - required: false
          schema:
            type: string
            title: Api-Key
          name: API-KEY
          in: header
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /ai/spec-populator/bulk-upload:
    post:
      summary: Upload Bulk Apis
      operationId: upload_bulk_apis_ai_spec_populator_bulk_upload_post
      parameters:
        - required: false
          schema:
            type: string
            title: Api-Key
          name: API-KEY
          in: header
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: Req
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /ai/spec-populator/bulk-remove:
    delete:
      summary: Remove Bulk Apis
      operationId: remove_bulk_apis_ai_spec_populator_bulk_remove_delete
      parameters:
        - name: API-KEY
          in: header
          required: false
          schema:
            type: string
            title: Api-Key
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /ai/api-design-assistant/chat:
    post:
      summary: Generate API specifications based on user input
      description: Generates API specifications based on user input and tracks session state.
      operationId: designAssistantChat
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: Natural language description of the API to be created
                  example: "create an API for a banking transaction."
                sessionId:
                  type: string
                  description: Unique identifier for the user session
                  example: "1234567890"
      responses:
        "200":
          description: Successful response with API specification.
          content:
            application/json:
              schema:
                type: object
                properties:
                  backendResponse:
                    type: string
                    description: List of suggestions for API improvements
                  isSuggestions:
                    type: boolean
                    description: Indicates if there are suggestions available
                  typeOfApi:
                    type: string
                    description: Detected type of API to be created
                  code:
                    type: string
                    description: Generated API specification
                  paths:
                    type: array
                    description: API endpoint paths and operations
                    items:
                      type: string
                  apiTypeSuggestion:
                    type: string
                    description: Suggested API type based on user input
                  missingValues:
                    type: string
                    description: Prompts for any required missing information
                  state:
                    type: string
                    description: Current state of the API generation process
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Invalid request. The 'text' field is missing or incorrectly named."
        "415":
          description: Unsupported Media Type (Invalid JSON format)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Request body must be in JSON format."
  /ai/api-design-assistant/generate-api-payload:
    post:
      summary: Generate API Payload
      description: Generate an API payload using the stored specification.
      operationId: designAssistantApiPayloadGen
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sessionId:
                  type: string
                  description: Session ID to retrieve the generated API specification
                  example: "1234567890"
      responses:
        "200":
          description: API payload successfully created.
          content:
            application/json:
              schema:
                type: string
                description: Generated payload for API
        "400":
          description: Invalid request or session ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message

components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
