# -------------------------------------------------------------------------------------
#
# Copyright (c) 2024, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

resources:
  repositories:
    - repository: common-templates
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      endpoint: wso2-enterprise

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - milvus_proxy_service/*
      - .azure/milvus-proxy-build.yaml

pr: none

jobs:
  - job: build
    displayName: Build/DockerPush
    pool:
      vmImage: "ubuntu-20.04"

    variables:
      - name: CONTAINER_REGISTRY
        value: choreocontrolplane.azurecr.io
      - name: REPOSITORY
        value: choreoipaas/milvus-proxy
      - name: DOCKER_BUILDKIT
        value: 1
      - name: APP_REVISION
        value: $(Build.SourceBranchName)-$(Build.SourceVersion)

    steps:
      - task: Docker@2
        displayName: "Docker Build"
        inputs:
          command: build
          containerRegistry: "wso2choreo-control-plane-acr"
          repository: $(REPOSITORY)
          Dockerfile: 'milvus_proxy_service/Dockerfile'
          buildContext: 'milvus_proxy_service'
          tags: |
            $(APP_REVISION)
            latest
      - template: install/install-trivy.yaml@common-templates
      - template: pr/trivy-scan.yaml@common-templates
        parameters:
          IMAGES:
            - $(CONTAINER_REGISTRY)/$(REPOSITORY):$(APP_REVISION)
          TRIVY_IGNORE_PATH: "milvus_proxy_service/.trivyignore"

      - task: Docker@2
        displayName: "Docker Push"
        inputs:
          command: push
          containerRegistry: "wso2choreo-control-plane-acr"
          repository: $(REPOSITORY)
          tags: |
            $(APP_REVISION)
            latest

      - template: update-image-in-cp-overlays.yml@common-templates
        parameters:
          CLUSTER_IMAGE_MAP:
            commonnamespacesdp:
              - $(CONTAINER_REGISTRY)/$(REPOSITORY):$(APP_REVISION)
            commonnamespacescombineddp:
              - $(CONTAINER_REGISTRY)/$(REPOSITORY):$(APP_REVISION)
