# -------------------------------------------------------------------------------------
#
# Copyright (c) 2024, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

resources:
  repositories:
    - repository: common-templates
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      endpoint: wso2-enterprise

trigger: none

pr:
  branches:
    include:
      - main
  paths:
    include:
      - milvus_proxy_service/*
      - .azure/milvus-proxy-pr-check.yaml

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: CONTAINER_REGISTRY
    value: 'choreocontrolplane.azurecr.io'
  - name: MILVUS_PROXY_REPOSITORY
    value: 'choreoipaas/milvus-proxy'

steps:

  - script: |
      echo "Repository var = $(MILVUS_PROXY_REPOSITORY)"
      echo "Listing milvus_proxy_service dir:"
      ls -R milvus_proxy_service || echo "milvus_proxy_service not found"
    displayName: "Debug variables and paths"

  - task: Docker@2
    displayName: 'Login to ACR'
    inputs:
      command: login
      containerRegistry: 'wso2choreo-control-plane-acr'

  - task: Docker@2
    displayName: 'Build Service Docker image'
    inputs:
      command: build
      containerRegistry: 'wso2choreo-control-plane-acr'
      repository: $(MILVUS_PROXY_REPOSITORY)
      Dockerfile: 'milvus_proxy_service/Dockerfile'
      buildContext: 'milvus_proxy_service'
      tags: |
        latest

  - template: install/install-trivy.yaml@common-templates
  - template: pr/trivy-scan.yaml@common-templates
    parameters:
      IMAGES:
        - $(CONTAINER_REGISTRY)/$(MILVUS_PROXY_REPOSITORY):latest
      TRIVY_IGNORE_PATH: "milvus_proxy_service/.trivyignore"
