trigger:
  branches:
    include:
    - '*'
    exclude:
    - main

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-20.04'

variables:
  SUPER_LINTER_VERSION: v4.10.1

steps:
- script: |
    docker run \
    -e RUN_LOCAL=true \
    -e VALIDATE_BASH=true \
    -e VALIDATE_DOCKERFILE=true \
    -e VALIDATE_DOCKERFILE_HADOLINT=true \
    -e VALIDATE_MD=true \
    -e VALIDATE_PYTHON_FLAKE8=true \
    -e VALIDATE_PYTHON_PYLINT=true \
    -e VALIDATE_YAML=true \
    -v $(System.DefaultWorkingDirectory):/tmp/lint github/super-linter:$(SUPER_LINTER_VERSION)
  displayName: 'Code Scan using GitHub Super-Linter'
