// Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
//
// This software is the property of WSO2 Inc. and its suppliers, if any.
// Dissemination of any information or reproduction of any material contained
// herein is strictly forbidden, unless permitted by WSO2 in accordance with
// the WSO2 Commercial License available at http://wso2.com/licenses.
// For specific language governing the permissions and limitations under
// this license, please see the license as well as any agreement you’ve
// entered into with WSO2 governing the purchase of this software and any
import ballerinax/ai.agent;

# A raw test case generated by the agent
type TestCase record {|
    # Name of the tool (mapped to the API resource)
    string tool;
    # Input parameters for the tool
    map<json> tool_input = {};
|};

# A test case mapped to the API resource
type ApiResourceSpecification record {|
    # HTTP method of the resource
    string method;
    # Path of the resource
    string path;
    # Input parameters for the resource
    map<json> inputs = {};
|};

# A test execution step. Stores the reasoning by the agent and http responses from the test run.
type TestExecutionStep record {|
    *agent:ExecutionStep;
    # HTTP response from a single test run
    HttpResponse observation;
|};

# A test execution report. Stores the API resource and the test execution steps.
type NextAction record {|
    # Thought generated by the agent
    string thought;
    # API resource executed by the agent
    ApiResourceSpecification 'resource;
|};

# Contains the spec for a single API resource
type ApiResource readonly & record {|
    # The path of the resource
    string path;
    # The HTTP method of the resource
    string method;
    # The spec of the resource
    agent:Operation spec;
|};

# Contains generated descriptions for a single API resource
type ApiResourceDescriptor record {|
    # The path of the resource
    string path;
    # The HTTP method of the resource
    string method;
    # The generated description for the resource
    string description;
|};

type GeneratedQuerySet record {|
    string singleResourceCall;
    string multiResourceCall;
|};

# Sample query record
type SampleQuery record {|
    # scenario
    string scenario;
    # query generated
    string query;
|};

# Cached record with progress
type CacheRecord record {|
    # current iteration
    int iteration;
    # command to be executed
    string command;
    # api specification
    agent:HttpApiSpecification apiSpec;
    # execution history of the test agent
    TestExecutionStep[] executionHistory;
    # thought during previous execution
    string previousThought;
|};

type HttpResponse record {
    # HTTP status code of the response
    int code;
    # Response headers 
    record {
        # Content type of the response
        string contentType?;
        # Content length of the response
        int contentLength?;
    } headers;
    # Response payload
    json|xml body?;
};
